import React, { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import BlogEditor from '../components/BlogEditor';
import AIWritingAssistant from '../components/AIWritingAssistant';
import IntelligentDraftManager from '../components/IntelligentDraftManager';
import { motion, AnimatePresence } from 'framer-motion';
import { useAuth } from '../contexts/AuthContext';
import { login as apiLogin, isAuthenticated as checkAuth } from '../services/auth';
import { isFeatureEnabled, FeatureGate } from '../config/features';

// Debug logging
console.log('🚨 AdminPage Debug:', {
  aiWritingAssistant: isFeatureEnabled('AI_WRITING_ASSISTANT'),
  aiDraftIntelligence: isFeatureEnabled('AI_DRAFT_INTELLIGENCE'),
  viteEnvMode: import.meta.env.VITE_DEPLOYMENT_MODE,
  viteAiAssistant: import.meta.env.VITE_ENABLE_AI_WRITING_ASSISTANT,
  viteDraftIntel: import.meta.env.VITE_ENABLE_AI_DRAFT_INTELLIGENCE
});

function BlogEditorPage({ isMobile }) {
  const { isAuthenticated: contextAuth, login: contextLogin } = useAuth();
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [activeView, setActiveView] = useState('editor'); // 'editor', 'ai', or 'drafts'
  const [aiGeneratedContent, setAiGeneratedContent] = useState(null);
  const navigate = useNavigate();
  const { id } = useParams(); // Get the post ID from URL if editing

  // Check if already authenticated
  useEffect(() => {
    // Check both API auth and legacy session auth
    const hasApiAuth = checkAuth();
    const hasSessionAuth = sessionStorage.getItem('blogAdminAuth') === 'authenticated';

    if (hasApiAuth || hasSessionAuth) {
      setIsAuthenticated(true);
      // If on /admin root and authenticated, redirect to dashboard
      if (window.location.pathname === '/admin') {
        navigate('/admin/dashboard');
      }
    }
  }, [contextAuth, navigate]);

  const handleLogin = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    
    try {
      // Try API login first
      const result = await apiLogin(password);
      if (result.success) {
        setIsAuthenticated(true);
        // Keep session storage for backward compatibility
        sessionStorage.setItem('blogAdminAuth', 'authenticated');
        setError('');
        navigate('/admin/dashboard');
      }
    } catch (error) {
      // Fallback to hardcoded password for backward compatibility
      if (password === 'lauriepickleball2024') {
        setIsAuthenticated(true);
        sessionStorage.setItem('blogAdminAuth', 'authenticated');
        setError('');
        navigate('/admin/dashboard');
      } else {
        setError(error.message || 'Incorrect password');
      }
    } finally {
      setLoading(false);
    }
  };

  const handleLogout = async () => {
    try {
      // Use the auth service logout directly
      const { logout } = await import('../services/auth');
      await logout();
    } catch (error) {
      console.error('Logout error:', error);
    }
    sessionStorage.removeItem('blogAdminAuth');
    setIsAuthenticated(false);
    navigate('/');
  };

  // Handle content generated by AI
  const handleAIContentGenerated = (content) => {
    setAiGeneratedContent(content);
    setActiveView('editor'); // Switch to editor view
  };

  if (!isAuthenticated) {
    return (
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        style={{
          minHeight: '100vh',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          padding: '20px',
          backgroundColor: 'var(--background-color)'
        }}
      >
        <div style={{
          maxWidth: '400px',
          width: '100%',
          backgroundColor: 'white',
          padding: '40px',
          borderRadius: '12px',
          boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)'
        }}>
          <h2 style={{
            fontSize: '2rem',
            marginBottom: '30px',
            color: 'var(--primary-color)',
            textAlign: 'center'
          }}>
            Blog Admin Login
          </h2>
          
          <form onSubmit={handleLogin}>
            <div style={{ marginBottom: '20px' }}>
              <label style={{
                display: 'block',
                marginBottom: '8px',
                color: 'var(--text-color)',
                fontSize: '1rem'
              }}>
                Password
              </label>
              <input
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                style={{
                  width: '100%',
                  padding: '12px',
                  fontSize: '1rem',
                  border: '1px solid var(--border-color)',
                  borderRadius: '8px',
                  outline: 'none'
                }}
                placeholder="Enter admin password"
                autoFocus
              />
            </div>
            
            {error && (
              <div style={{
                color: 'red',
                marginBottom: '20px',
                fontSize: '0.9rem'
              }}>
                {error}
              </div>
            )}
            
            <button
              type="submit"
              disabled={loading}
              style={{
                width: '100%',
                padding: '12px',
                backgroundColor: 'var(--primary-color)',
                color: 'white',
                border: 'none',
                borderRadius: '8px',
                fontSize: '1.1rem',
                cursor: loading ? 'not-allowed' : 'pointer',
                opacity: loading ? 0.7 : 1
              }}
            >
              {loading ? 'Logging in...' : 'Login'}
            </button>
          </form>
        </div>
      </motion.div>
    );
  }

  return (
    <div style={{
      minHeight: '100vh',
      backgroundColor: 'var(--background-color)'
    }}>
      <div style={{
        backgroundColor: 'white',
        borderBottom: '1px solid var(--border-color)',
        padding: '20px'
      }}>
        <div style={{
          maxWidth: '1200px',
          margin: '0 auto'
        }}>
          <div style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: '20px'
          }}>
            <h1 style={{
              fontSize: '2rem',
              color: 'var(--primary-color)',
              margin: 0
            }}>
              Blog Admin Panel
            </h1>
            <button
              onClick={handleLogout}
              style={{
                padding: '8px 20px',
                backgroundColor: 'var(--secondary-color)',
                color: 'white',
                border: 'none',
                borderRadius: '6px',
                cursor: 'pointer'
              }}
            >
              Logout
            </button>
          </div>
          
          {/* Navigation Tabs */}
          <div style={{
            display: 'flex',
            gap: '10px',
            borderTop: '1px solid var(--border-color)',
            paddingTop: '15px'
          }}>
            <button
              onClick={() => setActiveView('editor')}
              style={{
                padding: '10px 20px',
                backgroundColor: activeView === 'editor' ? 'var(--primary-color)' : 'transparent',
                color: activeView === 'editor' ? 'white' : 'var(--text-color)',
                border: activeView === 'editor' ? 'none' : '1px solid var(--border-color)',
                borderRadius: '6px',
                cursor: 'pointer',
                transition: 'all 0.3s ease',
                fontSize: '1rem',
                fontWeight: activeView === 'editor' ? 'bold' : 'normal'
              }}
            >
              Blog Editor
            </button>
            
            {isFeatureEnabled('AI_WRITING_ASSISTANT') && (
              <button
                onClick={() => setActiveView('ai')}
                style={{
                  padding: '10px 20px',
                  backgroundColor: activeView === 'ai' ? 'var(--primary-color)' : 'transparent',
                  color: activeView === 'ai' ? 'white' : 'var(--text-color)',
                  border: activeView === 'ai' ? 'none' : '1px solid var(--border-color)',
                  borderRadius: '6px',
                  cursor: 'pointer',
                  transition: 'all 0.3s ease',
                  fontSize: '1rem',
                  fontWeight: activeView === 'ai' ? 'bold' : 'normal'
                }}
              >
                AI Assistant
              </button>
            )}
            
            {isFeatureEnabled('AI_DRAFT_INTELLIGENCE') && (
              <button
                onClick={() => setActiveView('drafts')}
                style={{
                  padding: '10px 20px',
                  backgroundColor: activeView === 'drafts' ? 'var(--primary-color)' : 'transparent',
                  color: activeView === 'drafts' ? 'white' : 'var(--text-color)',
                  border: activeView === 'drafts' ? 'none' : '1px solid var(--border-color)',
                  borderRadius: '6px',
                  cursor: 'pointer',
                  transition: 'all 0.3s ease',
                  fontSize: '1rem',
                  fontWeight: activeView === 'drafts' ? 'bold' : 'normal'
                }}
              >
                🧠 Draft Intelligence
              </button>
            )}
          </div>
        </div>
      </div>
      
      {/* Content Area with Animation */}
      <AnimatePresence mode="wait">
        {activeView === 'editor' ? (
          <motion.div
            key="editor"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            transition={{ duration: 0.3 }}
          >
            <BlogEditor
              isMobile={isMobile}
              initialContent={aiGeneratedContent}
              onContentUsed={() => setAiGeneratedContent(null)}
              editingPostId={id}
            />
          </motion.div>
        ) : activeView === 'ai' && isFeatureEnabled('AI_WRITING_ASSISTANT') ? (
          <motion.div
            key="ai"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            transition={{ duration: 0.3 }}
          >
            <AIWritingAssistant 
              onEditBlog={handleAIContentGenerated}
            />
          </motion.div>
        ) : activeView === 'drafts' && isFeatureEnabled('AI_DRAFT_INTELLIGENCE') ? (
          <motion.div
            key="drafts"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            transition={{ duration: 0.3 }}
          >
            <IntelligentDraftManager 
              isMobile={isMobile}
            />
          </motion.div>
        ) : null}
      </AnimatePresence>
    </div>
  );
}

export default BlogEditorPage;